Algoritmo "Exercicio01"

// Exercício 01 - DevStart PayLivre - Lógica de Programação.
// Solicite o endereço de uma pessoa e imprima o endereço na tela.

Var
// Seção de Declarações das variáveis 
   endereco: caractere
   
INICIO
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o seu endereço: ")
   leia(endereco)
   escreva("Seu Endereço é: " + endereco)

Fimalgoritmo