Algoritmo "Exercicio15"
// Exercício 15

Var
// Seção de Declarações das variáveis 
   numero, contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um número: ")
   leia(numero)
   
   contador <- 0
   enquanto contador < 11 faca
            escreval(numero, " x ", contador, " = ", numero * contador)
            contador <- contador + 1
   fimenquanto

Fimalgoritmo