Algoritmo "Exercicio13"
// Exercício 13

Var
// Seção de Declarações das variáveis 
   contador, valInicio, valLimite: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o valor de início: ")
   leia(valInicio)
   escreva("Digite o valor limite: ")
   leia(valLimite)
   
   para contador de valInicio ate valLimite faca
        se (contador % 3 = 0) entao
           escreval(contador)
        fimse
   fimpara

Fimalgoritmo