Algoritmo "Exercicio16"
// Exercício 16

Var
// Seção de Declarações das variáveis 
   nome, senha: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   enquanto ((nome <> "Marcos") e (senha <> "PayLivre")) faca
            escreva("Digite seu usuário: ")
            leia(nome)
            escreva("Digite sua senha: ")
            leia(senha)
   fimenquanto
   escreva("Seja bem-vindo")

Fimalgoritmo